# Generated by Django 5.2 on 2025-04-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='our_history',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_history1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_history2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
