# Generated by Django 5.2 on 2025-04-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_our_history3'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='our_history4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_history5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='our_history6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
